---
title: "Logistinė regresija"
author: "Vainius Gataveckas, Matas Gaulia, Dovydas Martinkus"
output:
   html_document: default
---


```{r, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)

y <- read_csv("diabetes.csv")


table(y$Outcome)
```



```{r}
# empirinės tikimybės

y_plot <- y %>% pivot_longer(1:8)


y_plot %>% ggplot(aes(value, Outcome)) +
  stat_summary(fun = mean, geom = "bar") +
  facet_wrap(vars(name), scales = "free") +
  scale_x_binned(n.breaks = 8) +
  theme_minimal()
```


```{r}
# stačiakampės diagramos
y <- y %>% mutate(Outcome = factor(Outcome))
y_plot <- y_plot %>% mutate(Outcome = factor(Outcome))

y_plot %>% ggplot(aes(Outcome, value, fill = Outcome)) +
  geom_boxplot() +
  facet_wrap(vars(name), scales = "free") +
  theme_minimal()
```


```{r}
library(caret)
library(yardstick)

model <- glm(
  formula = Outcome ~ ., family = binomial(logit),
  data = y
)

1-pchisq(model$null.deviance-model$deviance, model$df.null-model$df.residual) # globali nulinė hipotezė (tikėtinumo santykių testas likelihood ratio test)



1-pchisq(model$deviance,model$df.residual) # residual goodness-of-fit testas


# tikrinama, ar yra išskirtys
plot(cooks.distance(model))


confusionMatrix(factor(as.numeric(model$fitted.values > 0.5)), factor(y$Outcome),positive="1")


# plotas po ROC
y_2 <- y %>% mutate(pred = model$fitted.values)
roc_auc(y_2, Outcome, pred, event_level = "second")
```

```{r}
# multikolinearumo tikrinimas
signs <- (model$coefficients > 0)[-1]
name <- names(model$coefficients)[-1]

temp_model <- function(x) {
  x <- sym(x)
  temp_model <- glm(
    formula = Outcome ~ eval(x), family = binomial(logit),
    data = y)
  temp_model$coefficients[2] > 0
}


map(name,temp_model) == signs

# pašalinamas kintamasis kurio koeficiento ženklas modelyje neatitinka jo įtakos
model <- glm(
  formula = Outcome ~ Pregnancies + Glucose + SkinThickness + BMI + DiabetesPedigreeFunction + Age, family = binomial(logit),
  data = y
)
```




```{r}
# reikšminų kovariančių atranka
model_2 <- step(model,direction = "both")

anova(model, model_2, test = "Chisq") # modelis statistiškai reikšmingai nesiskiria nuo modelio su visomis kovariantėmis

model$aic
model_2$aic


confusionMatrix(factor(as.numeric(model_2$fitted.values > 0.5)), factor(y$Outcome),positive="1")


# koeficientų interpretacija
exp(coef(model_2))
exp(confint(model_2))
```




```{r}
# modelio kovariačių efektai
library(effects)
plot(predictorEffects(model_2))
```



```{r}
# ROC kreivė
library(cutpointr)

y_2 <- y %>% mutate(pred = model_2$fitted.values)

cp <- cutpointr(y_2, pred, Outcome,
  pos_class = "1", direction = ">=",
  method = maximize_metric, metric = youden
)


cp$roc_curve[[1]] %>%
  ggplot(aes(x = 1 - tnr, y = tpr)) +
  geom_path() +
  coord_equal() +
  geom_abline() +
  theme_bw() +
  xlab("1-Specificity") +
  ylab("Sensitivity")


roc_auc(y_2, Outcome, pred, event_level = "second")
```



```{r}
# dėl didelio TN skaičiaus ROC rezultatai gali būti per daug optimistiški, todėl papildomai naudojama PR kreivė
cutoff <- cp$roc_curve[[1]] %>%
  filter(tpr > 0.9) %>%
  pull(m) %>%
  max()

labels <- filter(cp$roc_curve[[1]], (m %in% c(max(m), cutoff))) %>% round(2)


cp$roc_curve[[1]] %>%
  ggplot(aes(x = tpr, y = tp / (fp + tp))) +
  geom_point(data = labels) +
  geom_text(data = labels, aes(label = x.sorted), nudge_y = 0.05) +
  geom_path() +
  coord_equal() +
  theme_bw() +
  xlab("Recall") +
  ylab("Precision")

# slenkstinių reikšmių parinkimas
# suskaičiuojamos optimalios slenkstinės reikšmės pagal Youden-J statistic ir pasirinkus ribą Sensitivity > 0.9
  # (t.y. siekiant aptikti bent 90% sergančiųjų)
```



```{r}
# palyginimas su probit modeliu
model_3 <- glm(
  formula = Outcome ~ Pregnancies + Glucose + BMI + DiabetesPedigreeFunction, family = binomial(probit),
  data = y
)


y_3 <- y %>% mutate(pred = model_3$fitted.values)


cp_2 <- cutpointr(y_3, pred, Outcome,
  method = maximize_metric, metric = F1_score
)


cp$roc_curve[[1]] %>%
  mutate(link = "logit") %>%
  rbind((cp_2$roc_curve[[1]] %>% mutate(link = "probit"))) %>%
  ggplot(aes(x = tpr, y = tp / (fp + tp), color = link)) +
  geom_path() +
  coord_equal() +
  theme_bw() +
  xlab("Specificity") +
  ylab("Sensitivity")
# skirtumų tarp modelių beveik nėra
```
