---
title: "Regresija įvykių skaičiui"
author: "Vainius Gataveckas, Matas Gaulia, Dovydas Martinkus"
output:
   html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r, message=FALSE}
# Duomenys
# https://www.kaggle.com/datasets/brajeshmohapatra/bike-count-prediction-data-set?select=train.csv

library(tidyverse)
library(AER)
library(MASS)
```


```{r}
tr <- read.csv("train.csv")
te <- read.csv("test.csv")
te$count <- te$casual + te$registered
full <- rbind(tr, te)

full <- full %>%
  dplyr::select(-c(casual, registered)) %>%
  mutate(
    hour = lubridate::hour(datetime)
  ) 
```


```{r}
full <- full %>%
  filter(hour %in% c(12,13,14)) %>% 
  dplyr::select(-c(hour,datetime)) %>%
  mutate(
    season = factor(season),
    holiday = factor(holiday),
    workingday = factor(workingday),
    weather = factor(weather)
  )

head(full)
```




```{r}
# Perdaromi mokymo ir testavimo duomenų rinkiniai
library(rsample)
full_split <- initial_split(full, prop = 0.9)
train <- training(full_split)
test <- testing(full_split)

#write_csv(train,"train_from_R.csv")
#write_csv(test,"test_from_R.csv")
```



```{r}
# Siekiant gauti tokius pat rezultatus duomenys nuskaitomi iš failų
train <- read_csv("train_from_R.csv")
  
test <- read_csv("test_from_R.csv")

train <- train %>%
    mutate(
    season = factor(season),
    holiday = factor(holiday),
    workingday = factor(workingday),
    weather = factor(weather)
  )

test <- test %>%
    mutate(
    season = factor(season),
    holiday = factor(holiday),
    workingday = factor(workingday),
    weather = factor(weather)
  )


min(test$count)

ggplot(train, aes(x = count)) +
  geom_histogram() +
  theme_minimal()


# Dispersija didesnė už vidurkį
mean(train$count)
var(train$count)
```


```{r}
train %>%
  mutate(count = log(count)) %>%
  dplyr::select(c(temp, atemp, windspeed, humidity, count)) %>%
  pivot_longer(-count) %>%
  ggplot(aes(x = value, y = count, colour = name)) +
  geom_point() +
  geom_smooth(se = F, color = "red") +
  facet_wrap(~name, scales = "free") +
  theme_minimal()
```


```{r}
# Tarpusavio koreliacijos
library(corrplot)

correlation_matrix <- train %>%
  dplyr::select(where(is.numeric)) %>%
  cor()

corrplot(correlation_matrix, order = "original", method = "color", type = "upper", diag = FALSE, tl.col = "black", addCoef.col = "black")

train <- train %>% dplyr::select(-c(temp))
```

```{r}
name <- full %>%
  dplyr::select(where(is.factor)) %>%
  names()

group <- function(x) {
  full %>%
    group_by(!!sym(x)) %>%
    summarize(mean = mean(count), var = var(count), n = n())
}

purrr::map(name, group)
```


```{r}
train %>%
  dplyr::select(c(season, holiday, workingday, weather, count)) %>%
  pivot_longer(-count) %>%
  ggplot(aes(x = value, y = count, group = value)) +
  geom_boxplot() +
  facet_wrap(~name, scales = "free") +
  theme_minimal()
```



```{r}
# Puasono modelis
model_1 <- glm(count ~ ., family = "poisson", data = train)
summary(model_1)

cat("Deviacija padalinta iš laisvės laipsnių: ", model_1$deviance / model_1$df.residual, "\n")
cat("Siekiama, kad būtų tarp 0.7 ir 1.3")

# Tikrinima hipotezė, kad modelis nėra per didelės dispersijos (tiesinės dispersijos funkcijos alternatyva)
dispersiontest(model_1, trafo = 1)
```

```{r}
model_2 <- glm(count ~ ., family = quasipoisson(), data = train)
summary(model_2)
```

```{r}
plot(cooks.distance(model_2))
tibble(fitted = model_2$fitted.values,resid = resid(model_2, "pearson") / sqrt(31.8)) %>%
  ggplot(aes(fitted, resid)) +
  geom_point(alpha = 0.1) +
  geom_smooth(se = F)
```



```{r }
# Modelio koeficientų reikšmės
est <- cbind(Estimate = exp(coef(model_2)), exp(confint(model_2)))
est
```


```{r}
library(effects)
plot(predictorEffects(model_2))
```


```{r}
# Modelio panaudojimas prognozėms naudojant testavimo duomenų aibę
test_with_pred <- test %>% mutate(count = count, pred = predict(model_2, test, type = "response"))

test_with_pred %>%
  dplyr::select(c(count, pred)) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(x = value, fill = name)) +
  geom_histogram(bins = 25) +
  theme_minimal() +
  facet_wrap(vars(name))
```


```{r}
library(yardstick)

rmse(test_with_pred, count, pred)
mae(test_with_pred, count, pred)
```




```{r}
# Palyginimui sudaromas neigiamas binominis modelis (kvadratinė dispersijos funkcija)
dispersiontest(model_1, trafo = 2)

model_3 <- glm.nb(count  ~ ., data = train)
summary(model_3)

cat("Deviacija padalinta iš laisvės laipsnių: ", model_3$deviance / model_3$df.residual, "\n")
```




```{r}
plot(cooks.distance(model_3))
tibble(fitted = model_2$fitted.values,resid = resid(model_3, "pearson")) %>%
  ggplot(aes(fitted, resid)) +
  geom_point(alpha = 0.1) +
  geom_smooth(se = F)
```



```{r}
# Galima pažingsninė regresija
model_3_step <- stepAIC(model_3)

# Gaunamas lygiai toks pat modelis
anova(model_3, model_3_step)
```


```{r }
est <- cbind(Estimate = exp(coef(model_3)), exp(confint(model_3)))
est
```


```{r}
plot(predictorEffects(model_3))
```


```{r}
test_with_pred <- test %>% mutate(count = count, pred = predict(model_3, test, type = "response"))

test_with_pred %>%
  dplyr::select(c(count, pred)) %>%
  pivot_longer(everything()) %>%
  ggplot(aes(x = value, fill = name)) +
  geom_histogram(bins=12) +
  theme_minimal() +
  facet_wrap(vars(name))
```


```{r}
library(yardstick)

rmse(test_with_pred, count, pred)
mae(test_with_pred, count, pred)
```


